### ISSUE TITLE
devise-fido-u2f produces in-line javascript and style in its views which is requires an 'unsafe-inline' Content Security Policy

### ISSUE THREAD

**Issue by brianewell** [CyberDeck/devise-fido-u2f#12]
[Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) is an added layer of security that helps to detect and mitigate certain attacks, including Cross Site Scripting and data injection attacks.

I found that a CSP default policy of `self` was incompatible with the devise-fido-usf gem because of the gem's use of inline Javascript and CSS within the following views:

- app/views/devise/fido_usf_authentications/new.html.erb
- app/views/devise/fido_usf_registrations/new.html.erb

I'm going to fork the project and give fixing this a shot.

**Comment by CyberDeck** [comment]
Hi @brianewell,

I fixed the templates to cope with the latest Content Security Policy stuff for Rails 5.2.
The [Example App](https://github.com/cyberdeck/devise-fido-u2f-example-app) was fixed as well. Please have a look at the Example App to see how it can be implemented with a default policy of `self`.
